name: ci
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: bufbuild/buf-setup-action@v1.6.0
        with:
          version: 1.1.0
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            .cache
          key: ${{ runner.os }}-connect-web-ci-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-ci-
      - name: make format
        run: make format
      - name: make build
        run: make build
      - name: make lint
        run: make lint
      - name: make test
        run: make test
      - name: make bench-codesize
        run: make bench-codesize
      - name: make checkgenerate
        run: make checkgenerate

