name: ci
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.6.0
        with:
          version: 1.1.0
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-ci-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-ci-
      - name: make
        run: make format build lint test bench checkdiff

