name: "Web Conformance"

on:
  push:
    branches: [main, "v*"]
    tags: ["v*"]
  pull_request:
    branches: [main, "v*"]
  workflow_dispatch:

permissions:
  contents: read

env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1

jobs:
  browser:
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, safari, firefox]
        client: [promise, callback]
        include:
          - os: ubuntu-22.04
          - browser: safari
            os: macos-12
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.browser }} ${{ matrix.client }}"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}/web-conformance/${{ github.sha }}
          restore-keys: ${{ runner.os }}/web-conformance
      - run: npm ci
      - run: npx turbo run conformance:${{matrix.browser}}:${{matrix.client}} --filter '@connectrpc/connect-web' --output-logs new-only --log-order stream
  node:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Node.js v16 does not provide all necessary fetch types by default
        node-version: [21.1.0, 20.9.0, 18.16.0]
        client: [promise, callback]
    name: "Node.js ${{ matrix.node-version }} ${{ matrix.client }}"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}/web-conformance/${{ github.sha }}
          restore-keys: ${{ runner.os }}/web-conformance
      - run: npm ci
      - run: npx turbo run conformance:node:${{matrix.client}} --filter '@connectrpc/connect-web' --output-logs new-only --log-order stream
