name: conformance
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  node:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20, 21]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-node-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-node-conformance-
      - name: testconnectnodeconformance
        run: make testconnectnodeconformance
  fastify:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20, 21]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-fastify-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-fastify-conformance-
      - name: testconnectfastifyconformance
        run: make testconnectfastifyconformance
  express:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20, 21]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-express-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-express-conformance-
      - name: testconnectexpressconformance
        run: make testconnectexpressconformance
  webchrome:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-chrome-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-chrome-conformance-
      - name: testwebchromeconformance
        run: make testwebchromeconformance
  webfirefox:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-firefox-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-firefox-conformance-
      - name: testwebfirefoxconformance
        run: make testwebfirefoxconformance
  websafari:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-safari-conformance-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-safari-conformance-
      - name: testwebsafariconformance
        run: make testwebsafariconformance
