name: Prep release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: "The type of release."
        required: true
        options:
          - major
          - minor
          - patch
        default: patch

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          # Fetch full depth so we can get history and compare
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: perpare version
        id: prepare
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')
          NEXT_VERSION=$(npx -y semver -i ${{ github.event.inputs.releaseType }} $CURRENT_VERSION)
          echo "::set-output name=currentVersion::v$CURRENT_VERSION"
          echo "::set-output name=nextVersion::v$NEXT_VERSION"
          echo "v$NEXT_VERSION" > version
      - name: build message
        uses: mikepenz/release-changelog-builder-action@2ef19db678c29357b2438963a1758eb9fd375a1e
        id: diff
        with:
          # See https://github.com/mikepenz/release-changelog-builder-action#advanced-workflow-specification for configuration options
          configuration: "release-notes-config.json"
          fromTag: ${{ steps.prepare.outputs.currentVersion }}
          toTag: HEAD
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: fail if no PRs to merge
        if: steps.diff.outputs.pull_requests == ''
        run: |
          echo 'No PRs available to release.' >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: create pr
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with: 
          commit-message: "Publishing ${{ steps.prepare.outputs.nextVersion }}"
          delete-branch: true
          title: "Prepare release ${{ steps.prepare.outputs.nextVersion }}"
          body: ${{ steps.diff.outputs.changelog }}
          labels: "release"

          